### ISSUE TITLE
Game exits with an error when trying to go in a direction when there is nothing in that direction

### ISSUE THREAD

**Issue by Zrp200** [andy-j/skirmish#6]
Note: I'm using the code from #4
* Going south when in the pet shop
* Going north three times in the The Great Field Of Midgaard
* Going east in The Midgaard Donation Room
* Going south in the Armory
* Going north in the General Store
* Going west in the dirt path
* Going north in the bar of divination

**Comment by andy-j** [comment]
Expected behaviour should be a message to the effect of 'you can't go that way'. I will create a branch to re-work the input handling.

**Comment by Zrp200** [comment]
```
main.rb:125:in `block in <main>': undefined method `colorize' for nil:NilClass (NoMethodError)
	from main.rb:124:in `loop'
	from main.rb:124:in `<main>'
```

**Comment by andy-j** [comment]
Resolved.
